version: '3.8'

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./ngnix/nginx.conf:/etc/nginx/nginx.conf
  
  # php:
  # mysql:
  # composer:
  # artisan:
  # npm: