version: '3.8'

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./ngnix/nginx.conf:/etc/nginx/nginx.conf
  
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated 

  # mysql:
  # composer:
  # artisan:
  # npm: