apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template: 
    metadata: 
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: alextldr/k8s-demo-users:latest
          env: 
            - name: AUTH_ADDRESS
              # value: "10.97.135.78"
              value: "auth-service.default"
