version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #  MONGO_INITDB_ROOTUSERNAME: alex
    #  MONGO_INITDB_ROOT_PASSWORD: secret
      # - MONGO_INITDB_ROOTUSERNAME=alex
    env_file:
      - ./env/mongo.env
#  backend: 

#  frontend:

volumes:
  data: